### ISSUE TITLE
build python documentation...

### ISSUE THREAD

**Issue by lewismc** [capstone-coal/pycoal#58] opened 2017-04-15 10:25 UTC
@xiaomei7 can you please investigate why the python documentation is not building.
Let me know if you are struggling and I can help...
Than you very much.

**Comment by ghost** [comment] 2017-04-16 08:18
my assumption is that the build failures (e.g., due to pylint) prevent the docs from being built. perhaps it would be possible to build the docs before running the tests.

**Comment by ghost** [comment] 2017-04-19 02:42
@lewismc possible solution in pull https://github.com/capstone-coal/pycoal/pull/68

**Comment by ghost** [comment] 2017-04-19 02:45
there's also this error in the [build log](https://travis-ci.org/capstone-coal/pycoal/jobs/223396479):
```
Uploading documentation (skip with "skip_upload_docs: true")
running upload_docs
creating build
creating build/docs
error: no files found in upload directory 'build/docs'
```

**Comment by ghost** [comment] 2017-04-23 03:15
I have verified that the service is enabled in the GitHub dashboard. I have also verified that our 0.2.0 [version](https://docs.readthedocs.io/en/latest/versions.html) is not detected.

@lewismc ~You might want to verify that your Read The Docs account [imports](https://docs.readthedocs.io/en/latest/getting_started.html#import-your-docs) the correct GitHub repository name. I don't believe I have access to the Read The Docs account for this project so I can't check things on that end. Their [documentation](https://read-the-docs.readthedocs.io/en/latest/webhooks.html#github) does say that,~
> The GitHub URL in your Read the Docs project must match the URL on GitHub. The URL is case-sensitive.

~It might have stopped working after we renamed it, although all the URLs within our source code appear to be correct. If that doesn't work, then we can continue to investigate this issue.~ We could also reach out to the [support](https://docs.readthedocs.io/en/latest/support.html) resources for help.

**Comment by ghost** [comment] 2017-04-23 03:19
Scratch that, the Read The Docs [project page](http://readthedocs.org/projects/pycoal/) appears to see the correct URL. I triggered a build manually and the docs were updated (with the commit that introduced my middle name), however the source code is not detected. Now that it is confirmed that the server is set up correctly, I'm gonna dig around in the source for problems.

**Comment by ghost** [comment] 2017-04-23 03:29
It's possible that the `.rst` files need to reference our fully-qualified modules, e.g., `pycoal.mineral.MineralClassification` rather than `mineral.MineralClassification`. However, since I can call `make html` successfully this may not be the problem either.

**Comment by ghost** [comment] 2017-04-23 03:31
There is also info on [deleting stale builds](https://docs.readthedocs.io/en/latest/builds.html#deleting-a-stale-or-broken-build-environment).

**Comment by ghost** [comment] 2017-04-24 11:49
@lewismc I set up my own Read The Docs account and got it to work on a branch in my fork:
http://coal.readthedocs.io/en/issue-58-build-documentation-test/

The first problem was that for some reason Read The Docs is not finding the right version. The second is that the class names apparently need to be fully qualified.

I can try to fix things in the PyCOAL account if you add me as `browtayl` in Dashboard → Admin → Maintainers.

**Comment by ghost** [comment] 2017-04-26 01:30
Fixed in [`development`](https://github.com/capstone-coal/pycoal/pull/73/) per pull https://github.com/capstone-coal/pycoal/pull/75.

**Closed as completed by ghost** 2017-04-26 01:30 UTC
Labels: enhancement, help wanted, documentation
