### ISSUE TITLE
Error installing Pycoal

### ISSUE THREAD

**Issue by heidiaclayton** [capstone-coal/pycoal#82] opened 2017-04-29 10:07 UTC
Hi guys,
I tried installing pycoal via "sudo pip install pycoal" and got this error:

```
Collecting pycoal
  Downloading pycoal-0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-RajUna/pycoal/setup.py", line 55, in <module>
        _read('README.md')
      File "/tmp/pip-build-RajUna/pycoal/setup.py", line 50, in _read
        return open(os.path.join(os.path.dirname(__file__), *rnames)).read()
    IOError: [Errno 2] No such file or directory: '/tmp/pip-build-RajUna/pycoal/README.md'
    
    ----------------------------------------
```

**Comment by ghost** [comment] 2017-04-30 11:03
Confirmed on the AWS machine:
```
[ec2-user@ip-172-31-28-45 ~]$ sudo pip install pycoal
Collecting pycoal
  Downloading pycoal-0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-rAFVRn/pycoal/setup.py", line 55, in <module>
        _read('README.md')
      File "/tmp/pip-build-rAFVRn/pycoal/setup.py", line 50, in _read
        return open(os.path.join(os.path.dirname(__file__), *rnames)).read()
    IOError: [Errno 2] No such file or directory: '/tmp/pip-build-rAFVRn/pycoal/README.md'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-rAFVRn/pycoal/
```
[Recommend](https://github.com/capstone-coal/pycoal/pull/73/#issuecomment-298202347) we release 0.5.0. Assigning to @lewismc for publishing to PyPi or revision. Note that I already updated the version numbers and pushed the 0.5.0 tag per https://github.com/capstone-coal/pycoal/wiki/Release.

**Comment by ghost** [comment] 2017-04-30 11:04
Just to clarify, the release would either confirm or disconfirm that this is still an issue with the latest codebase.

**Comment by heidiaclayton** [comment] 2017-04-30 11:08
I didn't get this error back when we first released 0.1.

**Comment by ghost** [comment] 2017-04-30 11:23
Seems to point to [these lines](https://github.com/capstone-coal/pycoal/blob/cfcb93ec7f10d661dcf154ee835c79c238035d2d/setup.py#L49-L57) which haven't changed in the past three tags.

**Comment by heidiaclayton** [comment] 2017-04-30 11:24
Maybe the path to the readme isn't correct anymore?

**Comment by ghost** [comment] 2017-04-30 11:33
`README.md` does not appear to have moved. However I don't really understand what those lines are doing.

**Comment by ghost** [comment] 2017-05-01 00:42
Looks like we could test the install locally, so we could try to debug this before a release:
https://packaging.python.org/installing/#installing-from-a-local-src-tree

**Comment by lewismc** [comment] 2017-05-01 02:56
ACK I can reproduce. Debugging right now.

**Comment by lewismc** [comment] 2017-05-19 00:33
I'm going to work on this and make sure it is OK.

**Closed as completed** 2017-05-19 16:03 UTC
Labels: bug, build
